trigger:
- master
  
pool:
  vmImage: ubuntu-latest
  
steps:
- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  displayName: 'S3 Upload website'
  inputs:
    awsCredentials: 'AWS-S3'
    regionName: 'eu-west-2'
    bucketName: jeroenbroekhuizen.tech
    globExpressions: |
      index.html
      assets/**
    filesAcl: 'public-read'